org.gradle.jvmargs=-Xmx4096M

mod_id=grounded

minecraft_version=1.20.1
enabled_platforms=fabric,forge

mod_version=1.20.1-0.1.1
maven_group=com.kalob.realisticsurvival

parchment_version = 1.20.1:2023.09.03
quilt_version = 0.20.0-beta.4

fabric_loader_version = 0.16.9
fabric_api_version = 0.92.2+1.20.1

forge_version = 1.20.1-47.2.1

cloth_version = 11.0.99

moonlight_version = 1.20-2.13.30